server:
  port: ${SERVER_PORT:8091}
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/digibnk}

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8090}
  realm: ${KEYCLOAK_ADMIN_REALM:master}
  username: ${KEYCLOAK_ADMIN_USER:admin}
  password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
  target-realm: ${KEYCLOAK_TARGET_REALM:digibnk}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
